remove git plugins

diff --git a/dot_config/shell/config b/dot_config/shell/config
--- a/dot_config/shell/config
+++ b/dot_config/shell/config
@@ -80,12 +80,86 @@ alias \
 
 # git
 alias \
+        g='git' \
+        ga='git add' \
+        gb='git branch' \
+        \
+        gd='git diff' \
         gdo='git diff origin/"$(git_current_branch)"' \
+        gdca='git diff --cached' \
         gdcao='git diff --cached origin/"$(git_current_branch)"' \
-        glogf='git_log_tree_fzf' \
+        \
+        gc='git commit -v' \
+        gc!='git commit -v --amend' \
+        gcmsg='git commit -m' \
+        \
+        gco='git checkout' \
+        gcob='git checkout -b' \
+        \
+        gcp='git cherry-pick' \
+        gcpa='git cherry-pick --abort' \
+        gcpc='git cherry-pick --continue' \
+        \
+        gf='git fetch' \
+        gfprune='git fetch --all --prune' \
+        \
+        gl='git pull'\
+        ggpull='git pull origin "$(git_current_branch)"' \
+        \
+        gm='git merge' \
+        gmt='git mergetool' \
+        \
+        gp='git push' \
+        ggpush='git push origin "$(git_current_branch)"' \
+        ggpush!='git push --force-with-lease origin "$(git_current_branch)"' \
+        \
+        gr='git remote' \
+        grv='git remote  -v' \
+        \
+        grb='git rebase' \
+        grba='git rebase --abort' \
+        grbc='git rebase --continue' \
+        \
+        greset='git reset' \
+        greset!='git reset --hard' \
+        gresetremote='git reset --hard origin/"$(git_current_branch)"' \
+        gpristine='git reset --hard && git clean -dffx' \
+        \
+        gst='git status' \
+        gsts='git status -sb' \
         gstf='git_status_fzf' \
+        \
+        gsta='git stash' \
+        gstaa='git stash apply' \
+        gstas='git stash show --text' \
+        gstal='git stash list' \
+        gstad='git stash drop' \
+        gstap='git stash pop' \
+        \
+        glg='git log --stat' \
+        glog='git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset"' \
+        glogs='git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --stat' \
+        glogf='git_log_tree_fzf' \
+        gwch='git whatchanged -p --abbrev-commit --pretty=medium' \
+        \
+        gsetup='git branch --set-upstream-to=origin/$(git_current_branch)' \
+        gcfg='git config --list' \
         gitroot='git rev-parse --show-toplevel' \
         cdgr='cd $(gitroot)';
+
+# Outputs the name of the current branch
+# Usage example: git pull origin $(git_current_branch)
+# Using '--quiet' with 'symbolic-ref' will not cause a fatal error (128) if
+# it's not a symbolic ref, but in a Git repo.
+git_current_branch() {
+  ref="$(git symbolic-ref --quiet HEAD 2> /dev/null)";
+  ret="$?";
+  if [ "$ret" -ne 0 ]; then
+    [ "$ret" -eq 128 ] && return;  # no git repo.
+    ref="$(git rev-parse --short HEAD 2> /dev/null)" || return;
+  fi
+  echo "${ref#refs/heads/}";
+}
 
 DEFAULT_GIT_TICKER="${DEFAULT_GIT_TICKER:-}"
 gcmsgj() {
@@ -109,22 +183,22 @@ clip() {
 ex() {
   if [ -f "$1" ] ; then
     case "$1" in
-      *.tar.bz2)   tar xjf "$1"     ;;
-      *.tar.gz)    tar xzf "$1"     ;;
-      *.bz2)       bunzip2 "$1"     ;;
-      *.rar)       unrar x "$1"     ;;
-      *.gz)        gunzip "$1"      ;;
-      *.tar)       tar xf "$1"      ;;
-      *.tbz2)      tar xjf "$1"     ;;
-      *.tgz)       tar xzf "$1"     ;;
-      *.zip)       unzip "$1"       ;;
-      *.Z)         uncompress "$1"  ;;
-      *.7z)        7z x "$1"        ;;
-      *)           [ -z "$1" ] && printf "Usage:\n\t%s [path-to-archive]\n" "$0" ||
-                                  echo "$1 cannot be extracted via ex" ;;
+    *.tar.bz2)   tar xjf "$1"     ;;
+    *.tar.gz)    tar xzf "$1"     ;;
+    *.bz2)       bunzip2 "$1"     ;;
+    *.rar)       unrar x "$1"     ;;
+    *.gz)        gunzip "$1"      ;;
+    *.tar)       tar xf "$1"      ;;
+    *.tbz2)      tar xjf "$1"     ;;
+    *.tgz)       tar xzf "$1"     ;;
+    *.zip)       unzip "$1"       ;;
+    *.Z)         uncompress "$1"  ;;
+    *.7z)        7z x "$1"        ;;
+    *)           [ -z "$1" ] && printf "Usage:\n\t%s [path-to-archive]\n" "$0" ||
+                                echo "$1 cannot be extracted via ex" ;;
     esac
   else
-    echo "$1 is not a valid file"
+    echo "$1 is not a valid file";
   fi
 }
 
