posix comp startxw

diff --git a/extras/bootstrap/tree/usr/bin/startxw b/extras/bootstrap/tree/usr/bin/startxw
--- a/extras/bootstrap/tree/usr/bin/startxw
+++ b/extras/bootstrap/tree/usr/bin/startxw
@@ -1,6 +1,4 @@
-#!/bin/bash
-# FIXME: remove select loop for posix compat
-# #!/bin/sh
+#!/bin/sh
 
 # usage: startxw SESSION [-- ARGS...]
 # SESSION         seesion to start if not specified run interactive mode
@@ -13,51 +11,50 @@ ENABLED_SESSIONS="${ENABLED_SESSIONS:-"i3 xmonad bspwm dwm awesome xfce qtile"}"
 #shellcheck disable=SC2086
 _sessions="$(command -V $ENABLED_SESSIONS 2> /dev/null | grep -v "not found" | cut -d' ' -f1 )"
 
+_print_sessions() {
+  echo "$_sessions" | awk '{print "  " NR ") " $0}'
+}
+
 _exit_err() {
-  echo "$1"
-  printf "Available sessions:\n"
-  #shellcheck disable=SC2086
-  printf "  - %s\n" $_sessions
+  [ -n "$1" ] && echo "$1"
+  echo "Available sessions:"
+  echo "$_sessions" | awk '{print "  " NR ") " $0}'
   exit 1;
 }
 
-if [ -n "$1" ]; then
-  _xsession="$(echo "$_sessions" | grep "^$1$" || echo "")"
-  if [ -z "$_xsession" ]; then
-    _exit_err "Bad session '$1'. Exiting!"
-  fi
-else
-  echo "Select session to start:"
+if [ -z "$1" ]; then
   trap 'exit 1' INT
-  select opt in $_sessions; do
-    if [ -z "$opt" ]; then
-      if [ "$REPLY" = 0 ]; then
-        exit 0;
-      fi
-      _session_reply="$(echo "$_sessions" | grep "$REPLY" || echo "")"
-      if [ "$(echo "$_session_reply" | wc -l)" -gt 1 ]; then
-        _exit_err "Ambigous selection matched: $(echo "$_session_reply" | xargs)";
-      fi
-      if [ -z "$_session_reply" ]; then
-        _exit_err "Bad session '$REPLY'. Exiting!";
-      fi
-      _xsession="$_session_reply";
-    else
-      _xsession="$opt";
-    fi
-    break;
-  done
+  echo "Select session to start: (Type 0 or press CTRL+C to abort)"
+  echo "$_sessions" | awk '{print "  " NR ") " $0}'
+  printf "Select name or no (defaut 1): "
+  read -r _choice </dev/tty
+  _choice="${_choice:-1}"
   trap - INT
+else
+  _choice="$1"
 fi
+
+case "$_choice" in
+  0)      _exit_err;;
+  [0-9]*) _xsession="$(echo "$_sessions" | awk "NR == $_choice" || echo "")";;
+  *)      _xsession="$(echo "$_sessions" | grep "$_choice" || echo "")"
+esac
+if [ "$(echo "$_xsession" | wc -l)" -ne 1 ]; then
+  _exit_err "Ambigous selection matched: $(echo "$_xsession" | xargs)";
+fi
+if [ -z "$_xsession" ]; then
+  _exit_err "Bad session '$_choice'. Exiting!";
+fi
+
 
 _log_dir="${XDG_CACHE_HOME:-$HOME/.cache}/xsessionlogs"
 mkdir -p "$_log_dir"
-
 # remove old logs
 _hist=5
 find "$_log_dir" -type f -printf "%T@:%p\n" | sort -nr | tail -n "+$_hist" | cut -d: -f2- | xargs rm || true
-
+# select log file
 _log_file="$_log_dir/$(date +'%F_%H-%M-%S').log"
 ln -sf "$_log_file" "$_log_dir/current.log"
+
 
 DESKTOP_SESSION="$_xsession" exec startx "$_startx_args" 2>&1 | ts '[%Y-%m-%d %H:%M:%S]' > "$_log_file" 2>&1
