remove chezmoi template from clip

diff --git a/dot_local/bin/executable_clip b/dot_local/bin/executable_clip
--- a/dot_local/bin/executable_clip
+++ b/dot_local/bin/executable_clip
@@ -30,20 +30,24 @@ When running trough te pipe 'set' is assumed.
 _EOF_
 }
 
-{{ if eq .chezmoi.os "android" -}}
-_clipboard_get() { termux-clipboard-get; }
-_clipboard_set() { termux-clipboard-set; }
-{{ else -}}
-_clipboard_get() { xclip -out -selection clipboard; }
-_clipboard_set() { xclip -in -selection clipboard; }
-{{- end }}
+if command -v xclip >/dev/null 2>&1; then
+  _clipboard_get() { xclip -out -selection clipboard; }
+  _clipboard_set() { xclip -in -selection clipboard; }
+elif [ -n "$TERMUX_VERSION" ] && command -v termux-clipboard-get >/dev/null 2>&1; then
+  _clipboard_get() { termux-clipboard-get; }
+  _clipboard_set() { termux-clipboard-set; }
+else
+  _help
+  echo "Could not find xclip or termux-clipboard-get" >&2
+  exit 1
+fi
 
 mode="$1"
 if [ -z "$mode" ]; then # if no mode selected
   if [ -t 0 ]; then     # if not running trough te pipe
-    mode=get
+    mode='get'
   else
-    mode=set
+    mode='set'
   fi
 fi
 [ "$#" -gt 0 ] && shift;
