wayland configuration - sway and hypr

diff --git a/dot_local/bin/executable_passwdmenu b/dot_local/bin/executable_passwdmenu
--- a/dot_local/bin/executable_passwdmenu
+++ b/dot_local/bin/executable_passwdmenu
@@ -8,12 +8,21 @@ if [[ $1 == "--type" ]]; then
 	shift
 fi
 
+if [[ -n $WAYLAND_DISPLAY ]]; then
+  dotool="ydotool type --file -"
+elif [[ -n $DISPLAY ]]; then
+  dotool="xdotool type --clearmodifiers --file -"
+else
+  echo "Error: No Wayland or X11 display detected" >&2
+  exit 1
+fi
+
 prefix=${PASSWORD_STORE_DIR-~/.password-store}
 password_files=( "$prefix"/**/*.gpg )
 password_files=( "${password_files[@]#"$prefix"/}" )
 password_files=( "${password_files[@]%.gpg}" )
 
-password=$(printf '%s\n' "${password_files[@]}" | rofi -p "password$([ "$typeit" = 1 ] && echo " (type)" || true)" -dmenu "$@")
+password=$(printf '%s\n' "${password_files[@]}" | rofi -p "password$(if [ "$typeit" = 1 ]; then echo " (type)"; fi)" -dmenu "$@")
 
 [[ -n $password ]] || exit
 
@@ -25,6 +34,6 @@ fi
 if [[ $typeit -eq 0 ]]; then
 	$pass_cmd show -c "$password" 2>/dev/null
 else
-	$pass_cmd show "$password" | { IFS= read -r pass; printf %s "$pass"; } |
+	$pass_cmd show "$password" | { IFS= read -r pass; printf %s "$pass"; } | $dotool
 		xdotool type --clearmodifiers --file -
 fi
